; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

	TITLE	C:\Users\Mathew\Dropbox\Muzzler\windows-sync\code-concepts\argument-testing\ArgsListTest\ArgsListTest\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	___@@_PchSym_@00@UfhvihUnzgsvdUwilkylcUnfaaoviUdrmwldhRhbmxUxlwvRxlmxvkghUzitfnvmgRgvhgrmtUzithorhggvhgUzithorhggvhgUwvyftUhgwzucOlyq@F753469DE809C153
;	COMDAT ___@@_PchSym_@00@UfhvihUnzgsvdUwilkylcUnfaaoviUdrmwldhRhbmxUxlwvRxlmxvkghUzitfnvmgRgvhgrmtUzithorhggvhgUzithorhggvhgUwvyftUhgwzucOlyq@F753469DE809C153
_BSS	SEGMENT
___@@_PchSym_@00@UfhvihUnzgsvdUwilkylcUnfaaoviUdrmwldhRhbmxUxlwvRxlmxvkghUzitfnvmgRgvhgrmtUzithorhggvhgUzithorhggvhgUwvyftUhgwzucOlyq@F753469DE809C153 DD 01H DUP (?)
_BSS	ENDS
END
